### ISSUE TITLE
expand / untemplate the template parameters before returning them

### ISSUE THREAD

**Issue by mhl** [everypolitician/mediawiki-page-replaceable_content#3]
It's useful to be able to use templates within template parameters, but this tool will just return such templates unexpanded in `params` at the moment. We can do this untemplating with the MediaWiki API, using one of these calls:

* https://www.mediawiki.org/wiki/API:Expandtemplates
* https://www.mediawiki.org/wiki/API:Parsing_wikitext

**Comment by lucychambers** [comment]
@mhl - is this still relevant?

**Comment by mhl** [comment]
The new approach we're taking to the prompt tools really mean that this entire gem is no longer relevant, but whether we remove the repo now or later, I think this issue is definitely WONTFIX
